import { sqliteTable, integer, text, real } from 'drizzle-orm/sqlite-core';

export const claims = sqliteTable('claims', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  policyId: text('policy_id').notNull(),
  claimNumber: text('claim_number').notNull().unique(),
  incidentDate: text('incident_date').notNull(),
  incidentDescription: text('incident_description').notNull(),
  incidentLocation: text('incident_location').notNull(),
  damageDescription: text('damage_description').notNull(),
  estimatedCost: real('estimated_cost').notNull(),
  documents: text('documents', { mode: 'json' }),
  photos: text('photos', { mode: 'json' }),
  status: text('status').notNull().default('submitted'),
  submittedAt: text('submitted_at').notNull(),
  reviewedAt: text('reviewed_at'),
  reviewedBy: text('reviewed_by'),
  approvedAmount: real('approved_amount'),
  rejectionReason: text('rejection_reason'),
  adminNotes: text('admin_notes'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const healthPlans = sqliteTable('health_plans', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  description: text('description').notNull(),
  coverageAmount: real('coverage_amount').notNull(),
  monthlyPremiumBase: real('monthly_premium_base').notNull(),
  features: text('features', { mode: 'json' }),
  deductible: real('deductible').notNull(),
  copayPercentage: real('copay_percentage').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const healthApplications = sqliteTable('health_applications', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  applicationNumber: text('application_number').notNull().unique(),
  fullName: text('full_name').notNull(),
  email: text('email').notNull(),
  phone: text('phone').notNull(),
  dateOfBirth: text('date_of_birth').notNull(),
  gender: text('gender').notNull(),
  address: text('address').notNull(),
  city: text('city').notNull(),
  state: text('state').notNull(),
  zipCode: text('zip_code').notNull(),
  height: text('height').notNull(),
  weight: text('weight').notNull(),
  preExistingConditions: text('pre_existing_conditions'),
  medications: text('medications'),
  smoker: text('smoker').notNull(),
  alcoholConsumption: text('alcohol_consumption'),
  exerciseFrequency: text('exercise_frequency'),
  familyMedicalHistory: text('family_medical_history'),
  emergencyContactName: text('emergency_contact_name').notNull(),
  emergencyContactPhone: text('emergency_contact_phone').notNull(),
  status: text('status').notNull().default('pending'),
  selectedPlanId: integer('selected_plan_id'),
  calculatedPremium: real('calculated_premium'),
  submittedAt: text('submitted_at').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const healthPolicies = sqliteTable('health_policies', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  applicationId: integer('application_id').notNull(),
  planId: integer('plan_id').notNull(),
  policyNumber: text('policy_number').notNull().unique(),
  policyholderName: text('policyholder_name').notNull(),
  email: text('email').notNull(),
  monthlyPremium: real('monthly_premium').notNull(),
  coverageAmount: real('coverage_amount').notNull(),
  startDate: text('start_date').notNull(),
  endDate: text('end_date').notNull(),
  status: text('status').notNull().default('active'),
  paymentStatus: text('payment_status').notNull(),
  renewalDate: text('renewal_date').notNull(),
  renewalReminderSent: text('renewal_reminder_sent').notNull().default('no'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const healthClaims = sqliteTable('health_claims', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  policyId: text('policy_id').notNull(),
  claimNumber: text('claim_number').notNull().unique(),
  treatmentDate: text('treatment_date').notNull(),
  hospitalName: text('hospital_name').notNull(),
  doctorName: text('doctor_name').notNull(),
  diagnosis: text('diagnosis').notNull(),
  treatmentDescription: text('treatment_description').notNull(),
  claimAmount: real('claim_amount').notNull(),
  documents: text('documents', { mode: 'json' }),
  status: text('status').notNull().default('submitted'),
  submittedAt: text('submitted_at').notNull(),
  reviewedAt: text('reviewed_at'),
  reviewedBy: text('reviewed_by'),
  approvedAmount: real('approved_amount'),
  rejectionReason: text('rejection_reason'),
  adminNotes: text('admin_notes'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const claimReports = sqliteTable('claim_reports', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  reportType: text('report_type').notNull(),
  startDate: text('start_date').notNull(),
  endDate: text('end_date').notNull(),
  totalClaims: integer('total_claims').notNull(),
  totalClaimedAmount: real('total_claimed_amount').notNull(),
  totalApprovedAmount: real('total_approved_amount').notNull(),
  claimsData: text('claims_data', { mode: 'json' }).notNull(),
  generatedAt: text('generated_at').notNull(),
});