import { db } from '@/db';
import { claims } from '@/db/schema';

async function main() {
    const sampleClaims = [
        {
            userId: 'user_001',
            policyId: 'POL-2024-001',
            claimNumber: 'CLM-2024-001',
            incidentDate: new Date('2024-12-15').toISOString(),
            incidentDescription: 'Rear-end collision at traffic light on Main Street',
            incidentLocation: '123 Main St, Springfield',
            damageDescription: 'Rear bumper severely damaged, trunk misaligned, rear lights broken. Structural damage to frame.',
            estimatedCost: 3500,
            documents: ['police-report.pdf', 'estimate.pdf'],
            photos: ['damage-rear.jpg', 'damage-trunk.jpg', 'scene-overview.jpg'],
            status: 'approved',
            submittedAt: new Date('2024-12-15T14:30:00').toISOString(),
            reviewedAt: new Date('2024-12-18T10:15:00').toISOString(),
            reviewedBy: 'admin_001',
            approvedAmount: 3200,
            rejectionReason: null,
            adminNotes: 'Approved after review of police report. Minor reduction due to pre-existing scratches on bumper.',
            createdAt: new Date('2024-12-15T14:30:00').toISOString(),
            updatedAt: new Date('2024-12-18T10:15:00').toISOString(),
        },
        {
            userId: 'user_002',
            policyId: 'POL-2024-002',
            claimNumber: 'CLM-2024-002',
            incidentDate: new Date('2024-12-20').toISOString(),
            incidentDescription: 'Windshield cracked by flying debris on highway',
            incidentLocation: 'Highway 101 near Exit 42',
            damageDescription: 'Large crack across windshield starting from passenger side, spreading to center. Requires full replacement.',
            estimatedCost: 500,
            documents: ['estimate.pdf'],
            photos: ['windshield-crack.jpg'],
            status: 'paid',
            submittedAt: new Date('2024-12-20T09:00:00').toISOString(),
            reviewedAt: new Date('2024-12-21T11:30:00').toISOString(),
            reviewedBy: 'admin_002',
            approvedAmount: 500,
            rejectionReason: null,
            adminNotes: 'Straightforward windshield replacement. Approved full amount. Payment processed.',
            createdAt: new Date('2024-12-20T09:00:00').toISOString(),
            updatedAt: new Date('2024-12-22T14:00:00').toISOString(),
        },
        {
            userId: 'user_003',
            policyId: 'POL-2023-456',
            claimNumber: 'CLM-2024-003',
            incidentDate: new Date('2024-12-22').toISOString(),
            incidentDescription: 'Vehicle broken into, personal items stolen from trunk',
            incidentLocation: 'Walmart Parking Lot, 456 Oak Ave',
            damageDescription: 'Driver side window smashed, lock mechanism damaged, interior glass shards throughout cabin.',
            estimatedCost: 1200,
            documents: ['police-report.pdf'],
            photos: ['broken-window.jpg', 'interior-damage.jpg'],
            status: 'under_review',
            submittedAt: new Date('2024-12-22T16:45:00').toISOString(),
            reviewedAt: new Date('2024-12-23T09:00:00').toISOString(),
            reviewedBy: 'admin_001',
            approvedAmount: null,
            rejectionReason: null,
            adminNotes: 'Police report received. Awaiting inventory list of stolen items and additional photos of interior.',
            createdAt: new Date('2024-12-22T16:45:00').toISOString(),
            updatedAt: new Date('2024-12-23T09:00:00').toISOString(),
        },
        {
            userId: 'user_004',
            policyId: 'POL-2024-789',
            claimNumber: 'CLM-2024-004',
            incidentDate: new Date('2024-12-25').toISOString(),
            incidentDescription: 'Minor fender bender in parking lot - shopping cart damage',
            incidentLocation: 'Target Store, 789 Elm Street',
            damageDescription: 'Small dent on driver side door, paint scratched. Cosmetic damage only.',
            estimatedCost: 2100,
            documents: null,
            photos: ['door-dent.jpg'],
            status: 'rejected',
            submittedAt: new Date('2024-12-25T11:20:00').toISOString(),
            reviewedAt: new Date('2024-12-26T10:00:00').toISOString(),
            reviewedBy: 'admin_002',
            approvedAmount: null,
            rejectionReason: 'Insufficient evidence provided. No witness statements or security footage. Damage appears to be older than reported incident date.',
            adminNotes: 'Claim denied due to lack of supporting evidence and inconsistencies in timeline.',
            createdAt: new Date('2024-12-25T11:20:00').toISOString(),
            updatedAt: new Date('2024-12-26T10:00:00').toISOString(),
        },
        {
            userId: 'user_005',
            policyId: 'POL-2024-001',
            claimNumber: 'CLM-2024-005',
            incidentDate: new Date('2024-12-28').toISOString(),
            incidentDescription: 'Side-swipe collision during lane change',
            incidentLocation: 'Intersection of 5th and Pine',
            damageDescription: 'Passenger side doors and fender scraped and dented, side mirror broken off, paint damage along entire right side.',
            estimatedCost: 7800,
            documents: ['police-report.pdf', 'witness-statement.pdf', 'estimate.pdf'],
            photos: ['side-damage-1.jpg', 'side-damage-2.jpg', 'broken-mirror.jpg', 'scene-photo.jpg'],
            status: 'under_review',
            submittedAt: new Date('2024-12-28T15:30:00').toISOString(),
            reviewedAt: new Date('2024-12-29T13:00:00').toISOString(),
            reviewedBy: 'admin_001',
            approvedAmount: null,
            rejectionReason: null,
            adminNotes: 'Comprehensive documentation provided. Requesting additional estimate from approved body shop before final approval.',
            createdAt: new Date('2024-12-28T15:30:00').toISOString(),
            updatedAt: new Date('2024-12-29T13:00:00').toISOString(),
        },
        {
            userId: 'user_002',
            policyId: 'POL-2024-002',
            claimNumber: 'CLM-2024-006',
            incidentDate: new Date('2024-12-30').toISOString(),
            incidentDescription: 'Hail damage to vehicle roof and hood',
            incidentLocation: '234 Maple Drive, residential area',
            damageDescription: 'Multiple dents across hood and roof from hailstorm. Approximately 15-20 impact points, ranging from small to medium size.',
            estimatedCost: 12000,
            documents: ['weather-report.pdf', 'estimate.pdf'],
            photos: ['roof-damage.jpg', 'hood-damage.jpg', 'dent-closeup.jpg'],
            status: 'submitted',
            submittedAt: new Date('2024-12-30T18:00:00').toISOString(),
            reviewedAt: null,
            reviewedBy: null,
            approvedAmount: null,
            rejectionReason: null,
            adminNotes: null,
            createdAt: new Date('2024-12-30T18:00:00').toISOString(),
            updatedAt: new Date('2024-12-30T18:00:00').toISOString(),
        },
        {
            userId: 'user_003',
            policyId: 'POL-2024-789',
            claimNumber: 'CLM-2024-007',
            incidentDate: new Date('2025-01-02').toISOString(),
            incidentDescription: 'Hit-and-run incident while parked overnight',
            incidentLocation: 'Street parking on 8th Avenue',
            damageDescription: 'Front left fender crushed, headlight assembly destroyed, bumper detached on left side, wheel alignment affected.',
            estimatedCost: 4500,
            documents: ['police-report.pdf'],
            photos: null,
            status: 'submitted',
            submittedAt: new Date('2025-01-02T08:30:00').toISOString(),
            reviewedAt: null,
            reviewedBy: null,
            approvedAmount: null,
            rejectionReason: null,
            adminNotes: null,
            createdAt: new Date('2025-01-02T08:30:00').toISOString(),
            updatedAt: new Date('2025-01-02T08:30:00').toISOString(),
        },
    ];

    await db.insert(claims).values(sampleClaims);
    
    console.log('✅ Claims seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});